# rxchef rustfmt.toml

# Maximale Zeilenlänge (100 ist Standard, 120 oft besser für breite Bildschirme)
max_width = 100

# Sortiert Module und Imports alphabetisch
reorder_imports = true
reorder_modules = true
