[package]
name = "rxchef_cli"
version = "0.0.1"
edition = "2021"
description = "Command-line interface for rxchef"
license = "Apache-2.0"
repository = "https://github.com/MichaelWeissDEV/rx-chef"

[[bin]]
name = "rxchef"
path = "src/main.rs"

[dependencies]
clap         = { version = "4.5", features = ["derive"] }
rxchef       = { version = "0.0.1", path = "../.." }
rxchef_store = { version = "0.0.1", path = "../store" }
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
serde_yaml   = "0.9"
base64       = "0.22"
chrono       = "0.4"
regex        = "1"
