//! Generate the complete operation reference from the runtime registry.
//!
//! Run `cargo run --example generate_operation_docs` after adding or changing
//! an operation. CI uses `--check` to reject stale generated documentation.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use rxchef::runtime::{data_type_name, operation_info, operation_names};

fn markdown_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('|', "\\|")
        .replace('\n', " ")
}

fn inline_code(value: &str) -> String {
    if value.is_empty() {
        "`<empty>`".to_string()
    } else if value.contains('`') {
        format!("``{value}``")
    } else {
        format!("`{value}`")
    }
}

fn render() -> Result<String, String> {
    let names = operation_names(None);
    let mut modules: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for name in &names {
        let info = operation_info(name)?;
        modules
            .entry(info.module.to_string())
            .or_default()
            .push(name.clone());
    }

    let mut out = String::new();
    out.push_str("# Operation reference\n\n");
    out.push_str("<!-- Generated by `cargo run --example generate_operation_docs`; do not edit manually. -->\n\n");
    out.push_str(&format!(
        "This reference contains all **{} operations** registered by rxchef. Operation names are accepted case-insensitively and in normalized forms such as `to_hex`, `to-hex`, and `ToHex`. Use `rxchef info <NAME>` for the same metadata in the terminal and add `--json` for machine-readable output.\n\n",
        names.len()
    ));
    out.push_str("Arguments are positional in the order shown. Omitted arguments use their defaults. CLI values are strings unless prefixed with `num:`, `bool:`, `hex:`, or `bytes:`. For named arguments use `rxchef run <OP> --arg NAME=VALUE`.\n\n");
    out.push_str("## Modules\n\n");
    for (module, operations) in &modules {
        out.push_str(&format!(
            "- [{}](#{}) ({} operations)\n",
            module,
            module
                .to_lowercase()
                .replace(|c: char| !c.is_alphanumeric(), "-"),
            operations.len()
        ));
    }

    for (module, operations) in modules {
        out.push_str(&format!("\n## {}\n\n", module));
        for name in operations {
            let info = operation_info(&name)?;
            out.push_str(&format!("### {}\n\n", info.name));
            if info.is_broken {
                out.push_str("!!! warning \"Optional backend unavailable\"\n\n    This operation is feature-gated and unavailable in the minimal documentation build. See the feature matrix for the required Cargo feature.\n\n");
            }
            out.push_str(info.description.trim());
            out.push_str("\n\n");
            out.push_str(&format!(
                "- Input: `{}`\n- Output: `{}`\n- CLI: `rxchef run \"{}\"`\n",
                data_type_name(info.input_type),
                data_type_name(info.output_type),
                info.name.replace('"', "\\\"")
            ));
            if info.args.is_empty() {
                out.push_str("- Arguments: none\n\n");
            } else {
                out.push_str("\n| # | Argument | Default | Description |\n|---:|---|---|---|\n");
                for (index, arg) in info.args.iter().enumerate() {
                    out.push_str(&format!(
                        "| {} | {} | {} | {} |\n",
                        index + 1,
                        markdown_escape(arg.name),
                        inline_code(&markdown_escape(arg.default_value)),
                        markdown_escape(arg.description)
                    ));
                }
                out.push('\n');
            }
        }
    }
    Ok(out)
}

fn main() -> Result<(), String> {
    let check = env::args().skip(1).any(|arg| arg == "--check");
    let output = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("docs/reference/operations.md");
    let rendered = render()?;

    if check {
        let current = fs::read_to_string(&output)
            .map_err(|error| format!("cannot read {}: {error}", output.display()))?;
        if current != rendered {
            return Err(format!(
                "{} is stale; run `cargo run --example generate_operation_docs`",
                output.display()
            ));
        }
        println!(
            "operation documentation is current ({} operations)",
            operation_names(None).len()
        );
        return Ok(());
    }

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).map_err(|error| error.to_string())?;
    }
    fs::write(&output, rendered).map_err(|error| error.to_string())?;
    println!("generated {}", output.display());
    Ok(())
}
