/*
 * -----------------------------------------------------------------------------
 * Project:     rxchef
 * Version:     1.0.0
 * Author:      Michael Weiss
 * Source:      Ported from GCHQ's CyberChef (JavaScript)
 * License:     Apache-2.0
 * Description: Implementation of the Analyse hash operation.
 * -----------------------------------------------------------------------------
 */

use crate::operation::{DataType, Operation, OperationError};

/// Analyse hash operation
pub struct AnalyseHash;

impl Operation for AnalyseHash {
    fn name(&self) -> &'static str {
        "Analyse hash"
    }

    fn module(&self) -> &'static str {
        "Crypto"
    }

    fn description(&self) -> &'static str {
        "Tries to determine information about a given hash and suggests which algorithm may have been used to generate it based on its length."
    }

    fn args_schema(&self) -> &'static [crate::operation::ArgSchema] {
        &[]
    }

    fn input_type(&self) -> DataType {
        DataType::String
    }

    fn output_type(&self) -> DataType {
        DataType::String
    }

    fn run(
        &self,
        input: Vec<u8>,
        _args: &[crate::operation::ArgValue],
    ) -> Result<Vec<u8>, OperationError> {
        let input_str = String::from_utf8(input)
            .map_err(|_| OperationError::InvalidInput("Invalid UTF-8".to_string()))?;
        let input = input_str.replace(" ", "");

        // Validate input is valid hex
        if !input.chars().all(|c| c.is_ascii_hexdigit()) {
            return Err(OperationError::InvalidInput("Invalid hash".to_string()));
        }

        let byte_length = input.len() as u32 / 2;
        let bit_length = byte_length * 8;

        let mut output = String::new();
        output.push_str(&format!("Hash length: {}\n", input.len()));
        output.push_str(&format!("Byte length: {}\n", byte_length));
        output.push_str(&format!("Bit length:  {}\n\n", bit_length));
        output.push_str("Based on the length, this hash could have been generated by one of the following hashing functions:\n");

        let possible_hash_functions = match bit_length {
            4 => vec!["Fletcher-4", "Luhn algorithm", "Verhoeff algorithm"],
            8 => vec!["Fletcher-8"],
            16 => vec!["BSD checksum", "CRC-16", "SYSV checksum", "Fletcher-16"],
            32 => vec!["CRC-32", "Fletcher-32", "Adler-32"],
            64 => vec!["CRC-64", "RIPEMD-64", "SipHash"],
            128 => vec![
                "MD5",
                "MD4",
                "MD2",
                "HAVAL-128",
                "RIPEMD-128",
                "Snefru",
                "Tiger-128",
            ],
            160 => vec![
                "SHA-1",
                "SHA-0",
                "FSB-160",
                "HAS-160",
                "HAVAL-160",
                "RIPEMD-160",
                "Tiger-160",
            ],
            192 => vec!["Tiger", "HAVAL-192"],
            224 => vec!["SHA-224", "SHA3-224", "ECOH-224", "FSB-224", "HAVAL-224"],
            256 => vec![
                "SHA-256",
                "SHA3-256",
                "BLAKE-256",
                "ECOH-256",
                "FSB-256",
                "GOST",
                "Grstl-256",
                "HAVAL-256",
                "PANAMA",
                "RIPEMD-256",
                "Snefru",
            ],
            320 => vec!["RIPEMD-320"],
            384 => vec!["SHA-384", "SHA3-384", "ECOH-384", "FSB-384"],
            512 => vec![
                "SHA-512",
                "SHA3-512",
                "BLAKE-512",
                "ECOH-512",
                "FSB-512",
                "Grstl-512",
                "JH",
                "MD6",
                "Spectral Hash",
                "SWIFFT",
                "Whirlpool",
            ],
            1024 => vec!["Fowler-Noll-Vo"],
            _ => vec!["Unknown"],
        };

        output.push_str(&possible_hash_functions.join("\n"));

        Ok(output.into_bytes())
    }
}
