/*
 * -----------------------------------------------------------------------------
 * Project:     rxchef
 * Author:      Michael Weiss
 * Source:      Ported from GCHQ's CyberChef (JavaScript)
 * License:     Apache-2.0
 * Description: Implementation of the Bcrypt operation.
 * -----------------------------------------------------------------------------
 */

use bcrypt::{hash, DEFAULT_COST};

use crate::operation::{ArgSchema, ArgValue, DataType, Operation, OperationError};

/// Bcrypt operation
///
/// bcrypt is a password hashing function designed by Niels Provos and David Mazires,
/// based on the Blowfish cipher, and presented at USENIX in 1999. Besides incorporating
/// a salt to protect against rainbow table attacks, bcrypt is an adaptive function:
/// over time, the iteration count (rounds) can be increased to make it slower.
pub struct Bcrypt;

impl Operation for Bcrypt {
    fn name(&self) -> &'static str {
        "Bcrypt"
    }

    fn module(&self) -> &'static str {
        "Crypto"
    }

    fn description(&self) -> &'static str {
        "bcrypt is a password hashing function designed by Niels Provos and David Mazires, based on the Blowfish cipher, and presented at USENIX in 1999. Besides incorporating a salt to protect against rainbow table attacks, bcrypt is an adaptive function: over time, the iteration count (rounds) can be increased to make it slower."
    }

    fn args_schema(&self) -> &'static [ArgSchema] {
        static SCHEMA: &[ArgSchema] = &[ArgSchema {
            name: "Rounds",
            description: "Number of rounds (10-31, default 10)",
            default_value: "10",
            kind: crate::operation::ArgKind::UnsignedInteger,
            required: false,
            choices: &[],
            minimum: None,
            maximum: None,
            sensitive: false,
        }];
        SCHEMA
    }

    fn input_type(&self) -> DataType {
        DataType::String
    }

    fn output_type(&self) -> DataType {
        DataType::String
    }

    /// Generates a random salt for each hash.
    fn side_effects(&self) -> &'static [crate::operation::SideEffect] {
        use crate::operation::SideEffect;
        &[SideEffect::Random]
    }

    /// Equal inputs do not produce equal outputs.
    fn deterministic(&self) -> bool {
        false
    }

    fn run(&self, input: Vec<u8>, args: &[ArgValue]) -> Result<Vec<u8>, OperationError> {
        let rounds = args
            .get(0)
            .and_then(|a| a.as_f64())
            .map(|r| r as u32)
            .unwrap_or(DEFAULT_COST);

        // Validate rounds (must be between 4 and 31)
        if rounds < 4 || rounds > 31 {
            return Err(OperationError::InvalidArgument {
                name: "Rounds".to_string(),
                reason: "Rounds must be between 4 and 31".to_string(),
            });
        }

        let input_str = String::from_utf8(input)
            .map_err(|_| OperationError::InvalidInput("Invalid UTF-8".to_string()))?;

        let hashed =
            hash(input_str, rounds).map_err(|e| OperationError::ProcessingError(e.to_string()))?;

        Ok(hashed.into_bytes())
    }
}

#[cfg(test)]
mod tests {
    use bcrypt::{hash_with_salt, HashParts};

    #[test]
    fn fixed_salt_matches_independently_generated_bcrypt_vector() {
        // This vector was generated by an independent online bcrypt tool. Parse
        // only its salt, then require our fixed-salt core to reproduce its hash.
        let external = "$2a$04$UuTkLRZZ6QofpDOlMz32MuuxEHA43WOemOYHPz6.SjsVsyO1tDU96";
        let parsed: HashParts = external.parse().unwrap();
        let actual = hash_with_salt("password", 4, parsed.get_salt_raw()).unwrap();

        assert_eq!(
            actual.to_string(),
            "$2b$04$UuTkLRZZ6QofpDOlMz32MuuxEHA43WOemOYHPz6.SjsVsyO1tDU96"
        );
    }
}
