// Tests for the bcrypt_compare operation.
// Run only these tests:
//   cargo test -p cyberchef-rust-tests --test operations bcrypt_compare::

use rxchef::operation::ArgValue;
use rxchef::operations::bcrypt_compare::BcryptCompare;
use rxchef::Operation;

#[test]
fn test_bcrypt_compare_matches_independently_generated_vector() {
    let operation = BcryptCompare;
    // Generated by an independent online bcrypt implementation (cost 4).
    let args = [ArgValue::Str(
        "$2a$04$UuTkLRZZ6QofpDOlMz32MuuxEHA43WOemOYHPz6.SjsVsyO1tDU96".to_string(),
    )];

    assert_eq!(
        operation.run(b"password".to_vec(), &args).unwrap(),
        b"Match: password"
    );
}
#[test]
fn test_bcrypt_compare_no_match() {
    let operation = BcryptCompare;
    let args = [ArgValue::Str(
        "$2a$04$UuTkLRZZ6QofpDOlMz32MuuxEHA43WOemOYHPz6.SjsVsyO1tDU96".to_string(),
    )];
    let input = b"wrongpassword".to_vec();
    let result = operation.run(input, &args).unwrap();
    let output = String::from_utf8(result).unwrap();
    assert_eq!(output, "No match");
}

#[test]
fn test_bcrypt_compare_72_byte_password_boundary() {
    let operation = BcryptCompare;
    // Python bcrypt vector made from 100 'x' bytes. Bcrypt deliberately truncates
    // passwords at its 72-byte boundary, so exactly 72 bytes must also match.
    let args = [ArgValue::Str(
        "$2a$05$......................YgIDy4hFBdVlc/6LHnD9mX488r9cLd2".to_string(),
    )];
    let password = vec![b'x'; 72];

    assert_eq!(
        operation.run(password, &args).unwrap(),
        format!("Match: {}", "x".repeat(72)).into_bytes()
    );
}
#[test]
fn test_bcrypt_compare_invalid_hash() {
    let operation = BcryptCompare;
    let input = b"test".to_vec();
    let args = [ArgValue::Str("not_a_valid_hash".to_string())];
    let result = operation.run(input, &args);
    assert!(result.is_err());
}
